const STORAGE_KEY = 'stacked-poker-sessions';
const FIXED_ENTRY_AMOUNT = 10;
const SAVINGS_PER_NIGHT = 25;
const state = { period: 'night', anchor: new Date(2026, 8, 9), entries: loadEntries() };
const $ = (selector) => document.querySelector(selector);
const money = (value) => `$${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const key = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const formatDate = (date, options) => date.toLocaleDateString('en-US', options);
function loadEntries() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch { return {}; } }
function stats(entry) { const original = entry.original * FIXED_ENTRY_AMOUNT; const reentry = entry.reentry * FIXED_ENTRY_AMOUNT; const net = original * .5 + reentry * .7; return { original, reentry, entries: entry.original + entry.reentry, gross: original + reentry, house: original * .5 + reentry * .3, net, savings: SAVINGS_PER_NIGHT, available: net - SAVINGS_PER_NIGHT }; }
function addDays(date, amount) { const result = new Date(date); result.setDate(result.getDate() + amount); return result; }
function getRange() { if (state.period === 'night') return { start: state.anchor, end: state.anchor }; if (state.period === 'week') { const start = addDays(state.anchor, -((state.anchor.getDay() + 6) % 7)); return { start, end: addDays(start, 6) }; } return { start: new Date(state.anchor.getFullYear(), state.anchor.getMonth(), 1), end: new Date(state.anchor.getFullYear(), state.anchor.getMonth() + 1, 0) }; }
function getDays(range) { const days = []; for (let day = new Date(range.start); day <= range.end; day = addDays(day, 1)) days.push(new Date(day)); return days; }
function getRows(days) { return days.map((date) => ({ date, entry: state.entries[key(date)] || null, stats: state.entries[key(date)] ? stats(state.entries[key(date)]) : null })).filter((row) => row.entry); }
function renderRangeLabel(range) { const options = { month: 'short', day: 'numeric', year: 'numeric' }; if (state.period === 'night') $('#range-label').textContent = formatDate(range.start, { month: 'long', day: 'numeric', year: 'numeric' }); else $('#range-label').textContent = `${formatDate(range.start, options)} – ${formatDate(range.end, options)}`; $('#report-period').textContent = state.period === 'night' ? 'After Savings' : `After Savings · ${state.period}`; $('#chart-title').textContent = state.period === 'night' ? 'Nightly take-home' : `${state.period[0].toUpperCase()}${state.period.slice(1)}ly take-home`; }
function renderChart(days) { const values = days.map((date) => state.entries[key(date)] ? stats(state.entries[key(date)]).available : 0); const max = Math.max(...values, 1); $('#chart').innerHTML = values.some(Boolean) ? days.map((date, index) => `<div class="chart-bar-wrap"><div class="chart-bar" style="height:${Math.max(values[index] / max * 100, values[index] ? 4 : 0)}%" data-value="${money(values[index])}"></div><span class="chart-label">${formatDate(date, state.period === 'month' ? { day: 'numeric' } : { weekday: 'short' })}</span></div>`).join('') : '<div class="chart-empty">Add sessions to see your trend.</div>'; }
function renderBreakdown(rows) { $('#breakdown-count').textContent = `${rows.length} active night${rows.length === 1 ? '' : 's'}`; if (!rows.length) { $('#breakdown').innerHTML = '<div class="report-empty">There is no session data in this range yet.</div>'; return; } $('#breakdown').innerHTML = `<div class="breakdown-row breakdown-head"><span>NIGHT</span><span>ENTRIES</span><span>ORIGINALS</span><span>RE-ENTRIES</span><span>GROSS</span><span>YOUR TAKE</span></div>${rows.map((row) => `<div class="breakdown-row"><strong>${formatDate(row.date, { weekday: 'short', month: 'short', day: 'numeric' })}</strong><span>${row.stats.entries}</span><span>${row.entry.original}</span><span>${row.entry.reentry}</span><span class="breakdown-money">${money(row.stats.gross)}</span><strong class="breakdown-money breakdown-net">${money(row.stats.available)}</strong></div>`).join('')}`; }
function renderReport() { const range = getRange(); const days = getDays(range); const rows = getRows(days); const total = rows.reduce((sum, row) => { Object.keys(sum).forEach((name) => { sum[name] += row.stats[name] || 0; }); return sum; }, { entries: 0, original: 0, reentry: 0, gross: 0, house: 0, net: 0, savings: 0, available: 0 }); const activeNights = rows.length; const average = activeNights ? total.available / activeNights : 0; const best = rows.reduce((winner, row) => !winner || row.stats.available > winner.stats.available ? row : winner, null); renderRangeLabel(range); $('#report-net').textContent = money(total.available); $('#report-gross').textContent = money(total.gross); $('#report-savings').textContent = money(total.savings); $('#report-savings-nights').textContent = `$${SAVINGS_PER_NIGHT} × ${activeNights} active night${activeNights === 1 ? '' : 's'}`; $('#report-average').textContent = money(average); $('#report-best').textContent = money(best?.stats.available); $('#report-entry-count').textContent = `${total.entries} entr${total.entries === 1 ? 'y' : 'ies'}`; $('#report-active-nights').textContent = `${activeNights} active night${activeNights === 1 ? '' : 's'}`; $('#report-best-date').textContent = best ? formatDate(best.date, { month: 'short', day: 'numeric' }) : 'No sessions yet'; $('#insight-best').textContent = best ? `${money(best.stats.available)} on ${formatDate(best.date, { month: 'short', day: 'numeric' })}` : 'No sessions yet'; $('#insight-original').textContent = `${activeNights ? (total.original / FIXED_ENTRY_AMOUNT / activeNights).toFixed(1) : 0} per active night`; $('#insight-house').textContent = `${money(total.house)} retained`; const totalSplit = total.net + total.house; const netShare = totalSplit ? Math.round(total.net / totalSplit * 100) : 0; $('#net-share').textContent = `${netShare}%`; $('#house-share').textContent = `${100 - netShare}%`; $('#net-meter').style.width = `${netShare}%`; renderChart(days); renderBreakdown(rows); }
function moveRange(direction) { if (state.period === 'month') state.anchor = new Date(state.anchor.getFullYear(), state.anchor.getMonth() + direction, 1); else state.anchor = addDays(state.anchor, state.period === 'week' ? direction * 7 : direction); renderReport(); }
document.querySelectorAll('.period-tab').forEach((tab) => tab.addEventListener('click', () => { state.period = tab.dataset.period; document.querySelectorAll('.period-tab').forEach((item) => item.classList.toggle('active', item === tab)); renderReport(); }));
$('#previous-range').addEventListener('click', () => moveRange(-1)); $('#next-range').addEventListener('click', () => moveRange(1));
$('#export-report').addEventListener('click', () => { const rows = getRows(getDays(getRange())); const csv = [['Night', 'Original entries', 'Re-entries', 'Gross income', 'Python Poker cut', 'Your net income', 'Savings', 'Available after Savings'], ...rows.map((row) => [key(row.date), row.entry.original, row.entry.reentry, row.stats.gross.toFixed(2), row.stats.house.toFixed(2), row.stats.net.toFixed(2), row.stats.savings.toFixed(2), row.stats.available.toFixed(2)])]; const blob = new Blob([csv.map((row) => row.join(',')).join('\n')], { type: 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `stacked-${state.period}-report.csv`; link.click(); URL.revokeObjectURL(link.href); });
renderReport();
