const STORAGE_KEY = 'stacked-poker-sessions';
const FIXED_ENTRY_AMOUNT = 10;
const SAVINGS_PER_NIGHT = 25;
const state = { date: new Date(2026, 8, 9), selected: new Date(2026, 8, 9), entries: loadEntries() };
const $ = (selector) => document.querySelector(selector);
const money = (value) => `$${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const parseKey = (key) => { const [year, month, day] = key.split('-').map(Number); return new Date(year, month - 1, day); };
function loadEntries() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch { return {}; } }
function saveEntries() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.entries)); }
function getStats(entry) { const original = entry.original * FIXED_ENTRY_AMOUNT; const reentry = entry.reentry * FIXED_ENTRY_AMOUNT; const net = original * .5 + reentry * .7; return { original, reentry, gross: original + reentry, house: original * .5 + reentry * .3, net, savings: SAVINGS_PER_NIGHT, available: net - SAVINGS_PER_NIGHT }; }
function formatDate(date, options = { month: 'short', day: 'numeric', year: 'numeric' }) { return date.toLocaleDateString('en-US', options); }
function renderCalendar() { const year = state.date.getFullYear(); const month = state.date.getMonth(); $('#month-label').textContent = state.date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }); const first = new Date(year, month, 1); const offset = (first.getDay() + 6) % 7; const days = new Date(year, month + 1, 0).getDate(); const previous = new Date(year, month, 0).getDate(); let cells = ''; for (let index = 0; index < 42; index += 1) { const number = index - offset + 1; const date = new Date(year, month, number); const current = number > 0 && number <= days; const display = current ? number : number <= 0 ? previous + number : number - days; const key = dateKey(date); const entry = state.entries[key]; const classes = ['day', current ? 'current-month' : 'outside-month']; if (key === dateKey(state.selected)) classes.push('selected'); if (key === dateKey(new Date(2026, 8, 9))) classes.push('today'); cells += `<button class="${classes.join(' ')}" data-date="${key}"><span class="day-number">${display}</span>${entry ? `<i class="day-mark"></i><span class="day-amount">${money(getStats(entry).available)}</span>` : ''}</button>`; } $('#calendar-grid').innerHTML = cells; document.querySelectorAll('.day').forEach((day) => day.addEventListener('click', () => selectDate(parseKey(day.dataset.date)))); }
function selectDate(date) { state.selected = date; state.date = new Date(date.getFullYear(), date.getMonth(), 1); renderCalendar(); renderForm(); }
function renderForm() { const entry = state.entries[dateKey(state.selected)]; $('#selected-date').textContent = formatDate(state.selected, { weekday: 'long', month: 'long', day: 'numeric' }); $('#date-badge').textContent = `${String(state.selected.getMonth() + 1).padStart(2, '0')}.${String(state.selected.getDate()).padStart(2, '0')}`; $('#original-count').value = entry?.original ?? ''; $('#reentry-count').value = entry?.reentry ?? ''; $('#entry-amount').value = FIXED_ENTRY_AMOUNT.toFixed(2); $('#delete-button').hidden = !entry; updatePreview(); }
function updatePreview() { const stats = getStats({ original: Number($('#original-count').value) || 0, reentry: Number($('#reentry-count').value) || 0 }); $('#preview-net').textContent = money(stats.available); $('#preview-savings').textContent = money(stats.savings); }
function renderSummary() { const all = Object.values(state.entries); const totals = all.reduce((sum, entry) => { const current = getStats(entry); Object.keys(sum).forEach((key) => { sum[key] += current[key] || 0; }); return sum; }, { gross: 0, house: 0, net: 0, available: 0, savings: 0 }); $('#net-total').textContent = money(totals.available); $('#gross-total').textContent = money(totals.gross); $('#house-total').textContent = money(totals.house); $('#savings-total').textContent = money(totals.savings); $('#session-count').textContent = `${all.length} session${all.length === 1 ? '' : 's'} logged`; $('#month-change').textContent = all.length ? `${money(totals.available)} after Savings` : 'No entries yet'; const sorted = Object.entries(state.entries).sort(([a], [b]) => b.localeCompare(a)); $('#ledger-count').textContent = `${all.length} session${all.length === 1 ? '' : 's'}`; $('#ledger').innerHTML = sorted.length ? `<div class="ledger-row ledger-head"><span>DATE</span><span>ENTRIES</span><span>GROSS</span><span>YOUR TAKE</span><span>RATE</span></div>${sorted.slice(0, 8).map(([key, entry]) => { const current = getStats(entry); return `<div class="ledger-row"><strong>${formatDate(parseKey(key))}</strong><span>${entry.original} orig · ${entry.reentry} re</span><span class="ledger-money">${money(current.gross)}</span><strong class="ledger-money ledger-net">${money(current.available)}</strong><span>${money(FIXED_ENTRY_AMOUNT)}</span></div>`; }).join('')}` : '<div class="empty-state"><span>♠</span><p>Your dealt sessions will appear here.</p><small>Select a day on the calendar to add your first one.</small></div>'; }
$('#entry-form').addEventListener('submit', (event) => { event.preventDefault(); const entry = { original: Number($('#original-count').value) || 0, reentry: Number($('#reentry-count').value) || 0, amount: FIXED_ENTRY_AMOUNT }; if (!entry.original && !entry.reentry) return; state.entries[dateKey(state.selected)] = entry; saveEntries(); renderCalendar(); renderForm(); renderSummary(); });
$('#delete-button').addEventListener('click', () => { delete state.entries[dateKey(state.selected)]; saveEntries(); renderCalendar(); renderForm(); renderSummary(); });
document.querySelectorAll('#entry-form input').forEach((input) => input.addEventListener('input', updatePreview));
$('#previous-month').addEventListener('click', () => { state.date.setMonth(state.date.getMonth() - 1); renderCalendar(); }); $('#next-month').addEventListener('click', () => { state.date.setMonth(state.date.getMonth() + 1); renderCalendar(); }); $('#today-button').addEventListener('click', () => selectDate(new Date(2026, 8, 9)));
$('#export-button').addEventListener('click', () => { const rows = [['Date', 'Original entries', 'Re-entries', 'Amount per entry', 'Gross income', 'Python Poker cut', 'Your net income', 'Savings', 'Available after Savings']]; Object.entries(state.entries).forEach(([key, entry]) => { const stats = getStats(entry); rows.push([key, entry.original, entry.reentry, FIXED_ENTRY_AMOUNT.toFixed(2), stats.gross.toFixed(2), stats.house.toFixed(2), stats.net.toFixed(2), stats.savings.toFixed(2), stats.available.toFixed(2)]); }); const blob = new Blob([rows.map((row) => row.join(',')).join('\n')], { type: 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'stacked-poker-income.csv'; link.click(); URL.revokeObjectURL(link.href); });
renderCalendar(); renderForm(); renderSummary();
